create table TINH(MaTinh int primary key, TenTinh nchar(50))
create table HUYEN(MaHuyen int primary key, TenHuyen nchar(50), MaTinh int, FOREIGN KEY(MaTinh) REFERENCES dbo.TINH(MaTinh) )
drop table HUYEN
drop table DangkiKD
delete from dbo.TINH where MaTinh <> 1
delete TenTinh from dbo.TINH
create table HUYEN(MaHuyen int, TenHuyen nchar(50), MaTinh int, FOREIGN KEY(MaTinh) REFERENCES dbo.TINH(MaTinh) )
create table Users(Id int primary key,Username nchar(50), Password nchar(50), Ten nchar(50), Namsinh nchar(10), Gioitinh nchar(10), Roles int default 2, Madiaban int)
create table DangkiKD(Id int,TenhoKD nchar(100), MaTinh int , MaHuyen int , Diadiem nchar(100), SDT nchar(10), Email nchar(100), Website nchar(100), Nganhnghe nchar(100), Von nchar(20), Tendaidien nchar(100), Gioitinh nchar(10), Ngaysinh Date, CCCD nchar(10), Quoctich nchar(50), FOREIGN KEY(MaTinh) REFERENCES dbo.TINH(MaTinh)) 
alter table Chuho add MaTinh int
alter table Chuho add foreign key (MaTinh) references TINH(MaTinh)
alter table dbo.TINH drop column TenTinh
alter table dbo.TINH add TenTinh nchar(100)
alter table dbo.Users add primary key (Id)
insert into TINH(MaTinh,TenTinh)
values (3,'Hải Phòng'),
(4,'Đà Nẵng'),
(5,'Hà Giang'),
(6,'Cao Bằng'),
(7,'Lai Châu'),
(8,'Lào Cai'),
(9,'Tuyên Quang'),
(10,'Lạng Sơn'),
(11,'Bắc Kạn'),
(12,'Thái Nguyên'),
(13,'Yên Bái'),
(14,'Sơn La'),
(15,'Phú Thọ'),
(16,'Vĩnh Phúc'),
(17,'Quảng Ninh'),
(18,'Bắc Giang'),
(19,'Bắc Ninh'),
(21,'Hải Dương'),
(22,'Hưng Yên'),
(23,'Hòa Bình'),
(24,'Hà Nam'),
(25,'Nam Định'),
(26,'Thái Bình'),
(27,'Ninh Bình'),
(28,'Thanh Hóa'),
(29,'Nghệ An'),
(30,'Hà Tĩnh'),
(31,'Quảng Bình'),
(32,'Quảng trị'),
(33,'Thừa Thiên Huế'),
(34,'Quảng Nam'),
(35,'Quảng Ngãi'),
(36,'Kontum'),
(37,'Bình Định'),
(38,'Gia Lai'),
(39,'Phú Yên'),
(40,'Đắk Lắk'),
(41,'Khánh Hòa'),
(42,'Lâm Đồng'),
(43,'Bình Phước'),
(44,'Bình Dương'),
(45,'Ninh Thuận'),
(46,'Tây Ninh'),
(47,'Bình Thuận'),
(48,'Đồng Nai'),
(49,'Long An'),
(50,'Đồng Tháp'),
(51,'An Giang'),
(52,'Bà Rịa – VT'),
(53,'Tiền Giang'),
(54,'Kiên Giang'),
(55,'Cần Thơ'),
(56,'Bến Tre'),
(57,'Vĩnh Long'),
(58,'Trà Vinh'),
(59,'Sóc Trăng'),
(60,'Bạc Liêu'),
(61,'Cà Mau'),
(62,'Điện Biên'),
(63,'Đắk Nông'),
(64,'Hậu Giang')
insert into HUYEN(MaHuyen,TenHuyen, MaTinh)
values (1,N'Quận Ba Đình',1),
(2,N'Quận Hoàn Kiếm',1),
(3,N'Quận Hai Bà Trưng',1),
(4,N'Quận Đống Đa',1),
(5,N'Quận Tây Hồ',1),
(6,N'Quận Cầu Giấy',1),
(7,N'Quận Thanh Xuân',1),
(8,N'Quận Hoàng Mai',1),
(9,N'Quận Long Biên',1),
(10,N'Quận Bắc Từ Liêm',1),
(11,N'Huyện Thanh Trì',1),
(12,N'Huyện Gia Lâm',1),
(13,N'Huyện Đông Anh',1),
(14,N'Huyện Sóc Sơn',1),
(15,N'Quận Hà Đông',1),
(16,N'Thị xã Sơn Tây',1),
(17,N'Huyện Ba Vì',1),
(18,N'Huyện Phúc Thọ',1),
(19,N'Huyện Thạch Thất',1),
(20,N'Huyện Quốc Oai',1),
(21,N'Huyện Chương Mỹ',1),
(22,N'Huyện Đan Phượng',1),
(23,N'Huyện Hoài Đức',1),
(24,N'Huyện Thanh Oai',1),
(25,N'Huyện Mỹ Đức',1),
(26,N'Huyện Ứng Hòa',1),
(27,N'Huyện Thường Tín',1),
(28,N'Huyện Phú Xuyên',1),
(29,N'Huyện Mê Linh',1),
(30,N'Quận Nam Từ Liêm',1),
(1,N'Quận 1',2),
(2,N'Quận 2',2),
(3,N'Quận 3',2),
(4,N'Quận 4',2),
(5,N'Quận 5',2),
(6,N'Quận 6',2),
(7,N'Quận 7',2),
(8,N'Quận 8',2),
(9,N'Quận 9',2),
(10,N'Quận 10',2),
(11,N'Quận 11',2),
(12,N'Quận 12',2),
(13,N'Quận Gò Vấp',2),
(14,N'Quận Tân Bình',2),
(15,N'Quận Tân Phú',2),
(16,N'Quận Bình Thạnh',2),
(17,N'Quận Phú Nhuận',2),
(18,N'Quận Thủ Đức',2),
(19,N'Quận Bình Tân',2),
(20,N'Huyện Bình Chánh',2),
(21,N'Huyện Củ Chi',2),
(22,N'Huyện Hóc Môn',2),
(23,N'Huyện Nhà Bè',2),
(24,N'Huyện Cần Giờ',2),
(1,N'Quận Hồng Bàng',3),
(2,N'Quận Lê Chân',3),
(3,N'Quận Ngô Quyền',3),
(4,N'Quận Kiến An',3),
(5,N'Quận Hải An',3),
(6,N'Quận Đồ Sơn',3),
(7,N'Huyện An Lão',3),
(9,N'Huyện Thủy Nguyên',3),
(10,N'Huyện An Dương',3),
(11,N'Huyện Tiên Lãng',3),
(12,N'Huyện Vĩnh Bảo',3),
(13,N'Huyện Cát Hải',3),
(14,N'Huyện Bạch Long Vĩ',3),
(15,N'Quận Dương Kinh',3),
(8,N'Huyện Kiến Thụy',3),
(1,N'Quận Hải Châu',4),
(2,N'Quận Thanh Khê',4),
(3,N'Quận Sơn Trà',4),
(4,N'Quận Ngũ Hành Sơn',4),
(5,N'Quận Liên Chiểu',4),
(6,N'Huyện Hòa Vang',4),
(7,N'Quận Cẩm Lệ',4),
(8,N'Huyện Hoàng Sa',4),
(1,N'Thành phố Hà Giang',5),
(2,N'Huyện Đồng Văn',5),
(3,N'Huyện Mèo Vạc',5),
(4,N'Huyện Yên Minh',5),
(5,N'Huyện Quản Bạ',5),
(6,N'Huyện Vị Xuyên',5),
(7,N'Huyện Bắc Mê',5),
(8,N'Huyện Hoàng Su Phì',5),
(9,N'Huyện Xín Mần',5),
(10,N'Huyện Bắc Quang',5),
(11,N'Huyện Quang Bình',5),
(1,N'Thành phố Cao Bằng',6),
(2,N'Huyện Bảo Lạc',6),
(3,N'Huyện Thông Nông',6),
(4,N'Huyện Hà Quảng',6),
(5,N'Huyện Trà Lĩnh',6),
(6,N'Huyện Trùng Khánh',6),
(7,N'Huyện Nguyên Bình',6),
(8,N'Huyện Hòa An',6),
(9,N'Huyện Quảng Uyên',6),
(10,N'Huyện Thạch An',6),
(11,N'Huyện Hạ Lang',6),
(12,N'Huyện Bảo Lâm',6),
(13,N'Huyện Phục Hòa',6),
(1,N'Thành Phố Lai Châu',7),
(2,N'Huyện Tam Đường',7),
(3,N'Huyện Phong Thổ',7),
(4,N'Huyện Sìn Hồ',7),
(5,N'Huyện Mường Tè',7),
(6,N'Huyện Than Uyên',7),
(7,N'Huyện Tân Uyên',7),
(8,N'Huyện Nậm Nhùn',7),
(1,N'Huyện Bảo Thắng',8),
(2,N'Huyện Bảo Yên',8),
(3,N'Huyện Bát Xát',8),
(4,N'Huyện Bắc Hà',8),
(5,N'Thành phố Lào Cai',8),
(6,N'Huyện Mường Khương',8),
(7,N'Huyện Sa Pa',8),
(8,N'Huyện Si Ma Cai',8),
(9,N'Huyện Văn Bàn',8),
(1,N'Thành phố Tuyên Quang',9),
(2,N'Huyện Lâm Bình',9),
(3,N'Huyện Na Hang',9),
(4,N'Huyện Chiêm Hóa',9),
(5,N'Huyện Hàm Yên',9),
(6,N'Huyện Yên Sơn',9),
(7,N'Huyện Sơn Dương',9),
(1,N'Thành phố Lạng Sơn',10),
(2,N'Huyện Tràng Định',10),
(3,N'Huyện Bình Gia',10),
(4,N'Huyện Văn Lãng',10),
(5,N'Huyện Bắc Sơn',10),
(6,N'Huyện Văn Quan',10),
(7,N'Huyện Cao Lộc',10),
(8,N'Huyện Lộc Bình',10),
(9,N'Huyện Chi Lăng',10),
(10,N'Huyện Đình Lập',10),
(11,N'Huyện Hữu Lũng',10),
(1,N'Thành phố Bắc Kạn',11),
(2,N'Huyện Chợ Đồn',11),
(3,N'Huyện Bạch Thông',11),
(4,N'Huyện Na Rì',11),
(5,N'Huyện Ngân Sơn',11),
(6,N'Huyện Ba Bể',11),
(7,N'Huyện Chợ Mới',11),
(8,N'Huyện Pác Nặm',11)
insert into TINH(TenTinh)
values (N'Hà Nội'),
(N'TP Hồ Chí Minh'),
(N'Hải Phòng'),
(N'Đà Nẵng'),
(N'Hà Giang'),
(N'Cao Bằng'),
(N'Lai Châu'),
(N'Lào Cai'),
(N'Tuyên Quang'),
(N'Lạng Sơn'),
(N'Bắc Kạn'),
(N'Thái Nguyên'),
(N'Yên Bái'),
(N'Sơn La'),
(N'Phú Thọ'),
(N'Vĩnh Phúc'),
(N'Quảng Ninh'),
(N'Bắc Giang'),
(N'Bắc Ninh'),
(N'Hải Dương'),
(N'Hưng Yên'),
(N'Hòa Bình'),
(N'Hà Nam'),
(N'Nam Định'),
(N'Thái Bình'),
(N'Ninh Bình'),
(N'Thanh Hóa'),
(N'Nghệ An'),
(N'Hà Tĩnh'),
(N'Quảng Bình'),
(N'Quảng trị'),
(N'Thừa Thiên Huế'),
(N'Quảng Nam'),
(N'Quảng Ngãi'),
(N'Kontum'),
(N'Bình Định'),
(N'Gia Lai'),
(N'Phú Yên'),
(N'Đắk Lắk'),
(N'Khánh Hòa'),
(N'Lâm Đồng'),
(N'Bình Phước'),
(N'Bình Dương'),
(N'Ninh Thuận'),
(N'Tây Ninh'),
(N'Bình Thuận'),
(N'Đồng Nai'),
(N'Long An'),
(N'Đồng Tháp'),
(N'An Giang'),
(N'Bà Rịa – VT'),
(N'Tiền Giang'),
(N'Kiên Giang'),
(N'Cần Thơ'),
(N'Bến Tre'),
(N'Vĩnh Long'),
(N'Trà Vinh'),
(N'Sóc Trăng'),
(N'Bạc Liêu'),
(N'Cà Mau'),
(N'Điện Biên'),
(N'Đắk Nông'),
(N'Hậu Giang')
truncate table TINH